#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  BLEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  BREncoder,      sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotorF,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotorR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotorF,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightMotorR,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           hMotor1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           hMotor2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Storing Constants for Wheel Diameter and Pi
#define wheelDiameter 4
#define Pi 3.14159

int tickGoal=0;
int error;

#define liftDown 800
#define liftUp 2150
#define lift_pCoeff 0.2

#define MAX_POWER_OUT										127
#define MIN_POWER_OUT								  	-127

int actualLiftAngle;
int desiredLiftAngle;
int liftPowerOut;
int errorLiftAngle;
float liftIntegral;
const float integralLimit = 100;	// with respect to input
bool liftToggle;

int limitMotorPower(int power)																														//
{																																													//
	int	outputPower;																																				//
	//
	outputPower = power;																																		//
	if(outputPower > MAX_POWER_OUT)																													//
	{																																												//
		outputPower = MAX_POWER_OUT;																													//
	}																																												//
	else if(outputPower < MIN_POWER_OUT)																										//
	{																																												//
		outputPower = MIN_POWER_OUT;																													//
	}																																												//
	return(outputPower);																																		//
}

task liftControl()
{
	float kp = 0.2;
	float ki = .7;

	while(true)
	{
		if(liftToggle == true)
		{
			hogCPU();
			actualLiftAngle = SensorValue[pot];
			errorLiftAngle = (desiredLiftAngle - actualLiftAngle);

			// integral term
			if (abs(errorLiftAngle) < integralLimit) {
				liftIntegral += errorLiftAngle;
				} else {
				liftIntegral = 0;
			}
			liftPowerOut = (errorLiftAngle * lift_pCoeff);
			liftPowerOut = (kp * errorLiftAngle);// + (ki * liftIntegral);
			liftPowerOut = limitMotorPower(liftPowerOut);
			motor[liftMotor] = liftPowerOut;
			releaseCPU();
		}
		else
		{
			motor[liftMotor] = 0;
		}
		wait1Msec(20);
	}
}
void setLiftAngle(int liftAngle)																													//
{																																													//
	hogCPU();																																								//
	desiredLiftAngle = liftAngle;																														//
	liftIntegral = 0;																																				//
	releaseCPU();																																						//
}

void stopMotors ()
{
	motor[leftMotorF] = 0;
	motor[leftMotorR] = 0;
	motor[rightMotorF] = 0;
	motor[rightMotorR] = 0;
}


int inchToTicks (float inch)
{
	float wheelCircumference = wheelDiameter*Pi;
	int ticks = 360/wheelCircumference;
	tickGoal = (ticks * inch) / 10;
	return tickGoal;
}

//>>>>>>>>>>>>>>>>>>>>>>>>------------------0-----------------<<<<<<<<<<<<<<<<<<<<<<<<<

void PIDBaseControl (float target, float waitTime, float maxPower = 1)
{
	float kp = 0.3;
	//float ki = 0.055;
	float ki = 0;
	float kd= 2;
	float lastError;
	float proportional,derivative,integral;
	float output;
	target =inchToTicks(target);

	SensorValue[BLEncoder] = 0;
	SensorValue[BREncoder] = 0;

	error=10;

	while (true) {
		hogCPU();
		error = SensorValue[BLEncoder] - target;

		// proportional term
		proportional = error;

		// integral term
		if (abs(error) < integralLimit) {
			integral += error;
			} else {
			integral = 0;
		}

		// derivative term
		derivative = error - lastError;

		// output calculation
		output = (kp * proportional) + (ki * integral) + (kd * derivative);
		output = limitMotorPower(output);
		motor[leftMotorF] = -output;
		motor[leftMotorR] = -output;
		motor[rightMotorF] = -output;
		motor[rightMotorR] = -output;

		lastError = error;
		releaseCPU();
		wait1Msec(20);
	}
}

void PIDBaseTurn (float target, float waitTime, float maxPower = 1)
{
	float kp = 0.08;
	float ki = 0;
	float kd= 0;
	float lastError;
	float proportional,derivative,integral;
	float output;

	while (true) {
		hogCPU();
		error = SensorValue[gyro] - target;

		// proportional term
		proportional = error;

		// integral term
		if (abs(error) < integralLimit) {
			integral += error;
			} else {
			integral = 0;
		}

		// derivative term
		derivative = error - lastError;

		// output calculation
		output = (kp * proportional) + (ki * integral) + (kd * derivative);
		output = limitMotorPower(output);
		motor[leftMotorF] = output;
		motor[leftMotorR] = output;
		motor[rightMotorF] = -output;
		motor[rightMotorR] = -output;

		lastError = error;
		releaseCPU();
		wait1Msec(20);
	}
}

task main ()
{
	startTask(liftControl);
	setLiftAngle(liftUp);
	liftToggle = true;

	SensorValue[gyro]=0;
	wait1Msec(500);
	PIDBaseControl(240,0,.6); // move forward 10 inches with 0 sec delay;
	wait1Msec(500);
	/*setLiftAngle(liftDown);
	wait1Msec(500);
	PIDBaseControl(50,0,1); // move forward 3 inches with 0 sec delay;
	wait1Msec(500);
	setLiftAngle(liftUp);
	wait1Msec(500);
	PIDBaseControl(-130,0,.6); // move backwards 13 inches with 0 sec delay;
	wait1Msec(500);
	stopMotors();
	*/
}
