#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, PIDControl, driveRight, encoderPort, dgtl3)
#pragma config(Motor,  port4,           hMotor,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Storing Constants for Wheel Diameter and Pi
#define wheelDiameter 4
#define Pi 3.14

// Controller 1/2, Stick L/R, Axis X/Y
#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

//H-Drive using 4 Inputs
task hDrive(){
	while (true)
	{
		//Send Left Axis to Left Motors
		motor[leftMotor] = C1LY;
		//Send Right Axis to Right Motors
		motor[rightMotor] = C1RY;
		//Center Wheel Control
		motor[hMotor] = (vexRT[Btn5U] - vexRT[Btn6U])*127;

		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}

task main()
{
	startTask(hDrive);
	while (true)
	{
		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}
